changesDir: .changes
unreleasedDir: unreleased
changelogPath: CHANGELOG.md
versionExt: md
versionFormat: '## {{.Version}} - {{.Time.Format "2006-01-02"}}'
kindFormat: '### {{.Kind}}'
changeFormat: '* {{.Body}}'
kinds:
    - label: Added
      auto: major
    - label: Changed
      auto: major
    - label: Removed
      auto: major
    - label: Deprecated
      auto: minor
    - label: Enhanced
      auto: minor
    - label: Fixed
      auto: patch
    - label: Security
      auto: patch
newlines:
    afterKind: 1
    beforeKind: 1
    afterChangelogVersion: 2
    endOfVersion: 1
