// Code generated by go generate; DO NOT EDIT.
/*
 * Copyright (c) 2024. Dmitry Starov
 * SPDX-License-Identifier: MPL-2.0
 */

package function

import (
	"github.com/hashicorp/terraform-plugin-framework/function"

	genFuncs "github.com/dstaroff/terraform-provider-units/internal/provider/function/generated"
)

var GeneratedFunctions []func() function.Function

func init() {
	GeneratedFunctions = append(GeneratedFunctions,
		genFuncs.NewFromKibibytesModel,
		genFuncs.NewToKibibytesModel,
		genFuncs.NewFromMebibytesModel,
		genFuncs.NewToMebibytesModel,
		genFuncs.NewFromGibibytesModel,
		genFuncs.NewToGibibytesModel,
		genFuncs.NewFromTebibytesModel,
		genFuncs.NewToTebibytesModel,
		genFuncs.NewFromPebibytesModel,
		genFuncs.NewToPebibytesModel,
		genFuncs.NewFromKilobytesModel,
		genFuncs.NewToKilobytesModel,
		genFuncs.NewFromMegabytesModel,
		genFuncs.NewToMegabytesModel,
		genFuncs.NewFromGigabytesModel,
		genFuncs.NewToGigabytesModel,
		genFuncs.NewFromTerabytesModel,
		genFuncs.NewToTerabytesModel,
		genFuncs.NewFromPetabytesModel,
		genFuncs.NewToPetabytesModel,
	)
}
