// Code generated by go generate; DO NOT EDIT.
/*
 * Copyright (c) 2024. Dmitry Starov
 * SPDX-License-Identifier: MPL-2.0
 */

package converter

var DataSizeNames = []string{
	"bytes",
	"kibibytes",
	"mebibytes",
	"gibibytes",
	"tebibytes",
	"pebibytes",
	"kilobytes",
	"megabytes",
	"gigabytes",
	"terabytes",
	"petabytes",
}
