name: Changie

on:
  pull_request:
    paths:
      - .changes/unreleased/*.yaml
      - .changie.yaml
      - .github/workflows/changie.yml

permissions:
  contents: read

jobs:
  check:
    name: Ensure no diff
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Run Changie
        uses: miniscruff/changie-action@6dcc2533cac0495148ed4046c438487e4dceaa23 # v2.0.0
        with:
          version: latest
          args: batch patch --dry-run
