name: Test

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'

permissions:
  contents: read

jobs:
  generate:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Generate sources
        # language=bash
        run: |
          make generate

      - name: Ensure no diff
        # language=bash
        run: |
          git diff --compact-summary --exit-code || \
            (echo "*** Unexpected diff after code generation. Run 'make generate' and commit."; exit 1)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.9.4'
          terraform_wrapper: false

      - name: Generate docs
        # language=bash
        run: |
          make generate-docs

      - name: Ensure no diff
        # language=bash
        run: |
          git diff --compact-summary --exit-code || \
            (echo "*** Unexpected diff after code generation. Run 'make generate-docs' and commit."; exit 1)

  lint:
    name: Lint
    needs:
      - generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Lint
        uses: golangci/golangci-lint-action@aaa42aa0628b4ae2578232a66b541047968fac86 # v6.1.0
        with:
          version: latest

  test-unit:
    name: Test [unit]
    needs:
      - generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Test
        # language=bash
        run: |
          make test

  build:
    name: Build
    needs:
      - lint
      - test-unit
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Build
        # language=bash
        run: |
          make build

  test-acceptance:
    name: 'Test [Acc ${{ matrix.os-short }}:${{ matrix.terraform }}]'
    needs:
      - build
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
        terraform:
          - '1.8.*'
          - '1.9.*'
        include:
          - os: macos-latest
            os-short: macos
          - os: windows-latest
            os-short: windows
          - os: ubuntu-latest
            os-short: ubuntu
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Go
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: ${{ matrix.terraform }}
          terraform_wrapper: false

      - name: Run acceptance test
        # language=bash
        run: |
          make test-acceptance
